### ISSUE TITLE
Filter angry and sad mouths and eye from the avataaaar API

### ISSUE THREAD

**Issue by samuelandert** [circlesland/o-platform#192]
Remove mouths: "disbelive, grimace, sad, scream open, vomit"
Remove eyes: "dizzy, cry"

**Comment by samuelandert** [comment]
![62D49F3B-2426-4067-BF33-4ECEF4E53326](https://user-images.githubusercontent.com/747161/118791441-00ec7100-b897-11eb-81c5-4a27e8851d74.png)
There are still angry and sad faces

**Comment by jaensen** [comment]
should be fixed with 
f4ab89ac8c97c414a938bf6f18bb894752fe3569
5a2e3ca6a4c5f5d32259ba3e14ffd31d30095ba9
53b683999cb173e67a954278cc6a1dd7b0abdf3c
b9c861cf70dd252fc5a59f7b72ac7791b4a7ea5a

However, there are still some strange looking avatars around (mostly because "eating" can be mistaken for "almost vomiting" in some cases ;)
