### ISSUE TITLE
Fix firefox scrollbar on homepage

### ISSUE THREAD

**Issue by samuelandert** [circlesland/o-platform#256]
UPDATE: See last comment

On fireffox the layout "jumps" when the scrollbar is displayed (everything moves a bit to the left)
![grafik](https://user-images.githubusercontent.com/4954577/118693569-7448a100-b80b-11eb-9815-aef8bc8c703f.png)
![grafik](https://user-images.githubusercontent.com/4954577/118693603-7d397280-b80b-11eb-90a1-1144d54820fc.png)

**Comment by codeho** [comment]
as the scrollbar is a browser-window element, the left side of the scrollbar becomes the end of the viewport. 
its completely normal that if the window stays the same size, and there's a scrollbar appearing, the content 'jumps'.
it's doing this in all browsers i think. maybe safari does some auto-hiding of scrollbars, but also not always..
not sure if this can be fixed.
I'd not recommend a js based scrolling solution. they're always wonky and slow.

**Comment by jaensen** [comment]
I also think that we shouldn't necessarily attempt to fix that since its normal browser behavior and all possible fixes are somewhat not w3 standard and currently badly supported.

However the scrollbars here are pretty annoying
![grafik](https://user-images.githubusercontent.com/4954577/119507173-e28ee580-bd6e-11eb-8cef-7ddf4c8db035.png)
