### ISSUE TITLE
Catch the use case, where a user tries to trust themselves

### ISSUE THREAD

**Issue by samuelandert** [circlesland/o-platform#321]
Remove action buttons „trust“ and „send money“ when I open my own profile link

**Comment by jaensen** [comment]
There is no "Trust" or "Send money" button on the own profile page.
You can however enter your address manually in the first step of the corresponding context action in the safe.
This way you can transfer some xDai to yourself. CRC won't work because the max. flow determined by the pathfinder will be '0'.
Trusting yourself will fail with an error message and this should be catched.
