### ISSUE TITLE
Add fastlane for direct pathfinder requests

### ISSUE THREAD

**Issue by samuelandert** [circlesland/o-platform#406]

**Comment by jaensen** [comment]
- [ ] Instead of checking the pathfinder's maxflow before every transfer, check if the recipient directly trusts one or more of my tokens (assets).
- [ ] Sum up all accepted token balances with respect to the max. trust
- [ ] When the user entered the amount, check if the sum exceeds the amount
- [ ] Split the transfer amount among all trusted assets proportional to the balance of every asset
- [ ] Validate the transfer at the hub
- [ ] Send the hub transfer
