### ISSUE TITLE
TEST Invite / Registration Flow #2 - add Owner

### ISSUE THREAD

**Issue by codeho** [circlesland/o-platform#512]
- [ ] Import all Organisations where the key is Orga-Owner and add tor.us as other owner

**Comment by jaensen** [comment]
The issue was not directly with the TimeCircles conversion but it occurred in the following situations:

Scenario 1: "convertTimeCirclesToCircles()" returned too many decimal places for Web3's "toWei()" function.
Fix: execute "toFixed(12)" before returning the time circles.

Scenario 2: The contacts resolver in the api handled wei-values as js-number which resulted a string serialization in exponential form.
Fix: Handle wei-values as string/BN
