### ISSUE TITLE
transfer pipeline

### ISSUE THREAD

**Issue by codeho** [circlesland/o-platform#95]
- [x] Fix broken input field AGAIN.
- [x] Summary: Circle/s isntead of CRC?
- [x] Summary: add userprofile data if available
- [x] display profile recipient image

**Comment by codeho** [comment]
@jaensen: i need to get user firstname/lastname, and profilepicture in transfer.ts where we show the
'you are about to send xxx to xxx'. 
I'm not sure where/how i get this within the xstate without making a big mess :)
can you help?

**Comment by jaensen** [comment]
It would be nice if we could just use the complete object from the lookup selection instead of only a string/string key-value pair. But unfortunately this has its own problems with custom inputs (the custom input must be transformed to the same shape as the lookup object).
I will just add a separate api-call for now even if its a bit redundant.
